spring:
  profiles:
    active: dev #开发环境

  datasource:
    type: ${spring.datasource.type}
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.jdbc-url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bsoft.entity
  configuration:
    map-underscore-to-camel-case: true